### ISSUE TITLE
Ban?  Really?

### ISSUE THREAD

**Issue by Akrymir** [Oghma-Infinium/Twisted-Skyrim#2]
We disagreed on something so you banned me?  Dude, common... I was really looking forward to playing it too.  No one is going to agree with every choice you make, but people should be able to discuss it with you, or even be allowed to agree to disagree.  How is anyone suppose to talk to you honestly if they have to fear you banning them if they disagree?

**Comment by TwistedModding** [comment]
You and I both know thats not why I banned you. Out of respect for my own list I'm not banning you from here so if you find *actual* issues with the list you can report them. Anymore of this and I'll be banning you from the github as well.

**Comment by Akrymir** [comment]
I'm sorry if you took more out of it than what I just said, because that's all it really was, a difference of opinion.  Clearly this will get me banned here too because you see things differently... and if you're going to ban me for something that trivial then I clearly am not going to get any real support for the actual issues I'm currently having.

If the issue was what you made it out to be, I'd just be making a new discord account, instead of coming here.

**Comment by TwistedModding** [comment]
No, you insisted that you're opinion was correct for and that my choice of design was flawed by keeping the original leveling system of the game, which again you insisted was an issue that needed to be fixed. Which you clearly still don't understand how ignornant that is. Congrats on being the only person in 4 months of this server being open to actually get banned.
